spring:
  datasource:
    url: jdbc:h2:mem:sicppdb;MODE=MYSQL
    username: sa
    password:
    baseline-on-migrate: true
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop



