server:
  port: 8081

spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
  hibernate:
    format_sql: true
  properties:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
security:
  jwt:
    secret: JoHGKriR5ySkLPnUrDII1IOcH4qIke0oLAuWw+CAsmA=
    access-token-expiration: 900000        # 15 minutos
    refresh-token-expiration: 86400000     # 1 dia
